# Generated by Django 5.2.17 on 2026-09-10 16:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('group_name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(editable=False, max_length=254, unique=True)),
                ('rider_role', models.TextField(choices=[('Group Leader', 'group leader'), ('Rider', 'rider')], default='Rider')),
                ('blood_group', models.CharField(blank=True, choices=[('Select', 'select'), ('O-', 'o-'), ('O+', 'o+'), ('A-', 'a-'), ('A+', 'A+'), ('B-', 'b-'), ('B+', 'b+'), ('AB-', 'ab-'), ('AB+', 'ab+')], max_length=10, null=True)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(60)])),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider',
                'verbose_name_plural': 'Riders',
                'db_table': 'riders',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('chat_message', models.CharField(max_length=250)),
                ('message_type', models.CharField(choices=[('MESSAGE', 'message'), ('NOTIFICATION', 'notification'), ('ALERT', 'alert')], default='MESSAGE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='backend.group')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='backend.rider')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.group')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.rider')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to='backend.rider'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', through='backend.GroupMembership', to='backend.rider'),
        ),
        migrations.CreateModel(
            name='BikeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberplate', models.CharField(max_length=10)),
                ('bikename', models.CharField(default='mybike', max_length=20)),
                ('documents', models.URLField()),
                ('insurance', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='backend.rider')),
            ],
            options={
                'verbose_name': 'BikeInfo',
                'verbose_name_plural': 'BikeInfos',
                'db_table': 'bikeinfos',
            },
        ),
        migrations.CreateModel(
            name='RiderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('REST', 'rest'), ('FUELLING', 'fuelling'), ('ONROAD', 'onroad')], default='REST', max_length=20)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='backend.rider')),
            ],
        ),
        migrations.AddIndex(
            model_name='rider',
            index=models.Index(fields=['first_name', '-created_at'], name='riders_first_n_2c7722_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_id', '-created_at'], name='messages_message_94ef26_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('rider', 'group')},
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['group_id', '-group_name'], name='groups_group_i_de5f8b_idx'),
        ),
        migrations.AddIndex(
            model_name='bikeinfo',
            index=models.Index(fields=['rider_id', 'created_at'], name='bikeinfos_rider_i_15d246_idx'),
        ),
    ]
