# Generated by Django 5.2.17 on 2026-09-21 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bikeinfo',
            name='bikeinfos_rider_i_15d246_idx',
        ),
        migrations.AlterField(
            model_name='rider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bikeinfo',
            index=models.Index(fields=['rider', 'created_at'], name='bikeinfos_rider_i_15d246_idx'),
        ),
    ]
