# Generated by Django 5.2.17 on 2026-09-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_bikeinfo_bikeinfos_rider_i_15d246_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=14, max_digits=17),
        ),
        migrations.AlterField(
            model_name='riderlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=14, max_digits=17),
        ),
    ]
