# Generated by Django 5.2.17 on 2026-09-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_riderlocation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
        migrations.AlterField(
            model_name='riderlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
    ]
