# Generated by Django 5.2.17 on 2026-09-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_riderlocation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderlocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
